#!/usr/bin/env bash

if [ $# -ne 1 ]; then
    echo 'Usage: rsa <file>'
    exit 1
fi

file="$1"
if [ ! -f "$file" ]; then
    echo "File '$file' not found."
    exit 1
fi

# Read the number from the file
read -r number < "$file"

prime_factors=$(factor "$number" | awk '{print $2}' | tac | paste -sd '*')
echo "$number = $prime_factors"

