#!/usr/bin/env bash
#Challenge
# Check the command-line arguments
if [ $# -ne 1 ] || [ ! -f "$1" ]; then
    echo "Usage: rsa <file>"
    exit 1
fi

read -r number < "$1"

prime_factors=$(factor "$number" | awk '{for(i=2;i<=NF;i++) printf("%s%s", (i>2?" * ":""), $i)}')

echo "$number = $prime_factors"
